output_dir: '../../data/a549_dex/experiments'
module: src.experiments.seq_seq_domain_translation
class: SeqSeqTranslationExperiment
run_params:
  seq_data_config_1: {'data_fname':'../../data/a549_dex/processed/rna_data.csv',
                      'data_key':'seq_data',
                      'label_key':'label'}

  seq_model_config_1 : {'model_config':{'type':'VanillaAE',
                                        'hidden_dims':[1024, 512, 256, 128],
                                        'latent_dim': 50,
                                        'in_dims':2613},
                        'optimizer_config':{'type':'rmsprop', 'lr':0.00001, 'weight_decay':0.0005},
                        'loss_config':{'type':'mae'}}

  seq_data_config_2: {'data_fname':'../../data/a549_dex/processed/atac_data.csv',
                      'data_key':'seq_data',
                      'label_key':'label'}

  seq_model_config_2 : {'model_config':{'type':'VanillaAE',
                                        'hidden_dims':[512, 256, 128, 64],
                                        'latent_dim': 50,
                                        'in_dims':815},
                        'optimizer_config':{'type':'rmsprop', 'lr':0.00001, 'weight_decay':0.0005},
                        'loss_config':{'type':'mae'}}

  latent_dcm_config: {'model_config':{'type':'LatentDiscriminator', 'n_classes':2,
                      'latent_dim': 50, 'hidden_dims':[128, 128, 128,]},
                      'optimizer_config':{'type':'rmsprop', 'lr':0.00001},
                      'loss_config':{'type':'ce'}}

  latent_structure_model_config: {'model_config':{'type':'LatentClassifier',
                                      'latent_dim':50, 'n_classes':3},
                      'optimizer_config':{'type':'rmsprop', 'lr':0.00001},
                      'loss_config':{'type':'ce'}}

  num_epochs: 1000
  early_stopping: -1
  train_val_test_split: [0.7, 0.2, 0.1]
  batch_size: 32
  random_state: 1001
  paired_data: True
  latent_distance_loss: 'mae'
  latent_supervision_rate: 0.5


pipeline:
  - method: initialize_seq_data_set_1
  - method: initialize_seq_data_set_2
  - method: get_and_set_paired_training_idc
  - method: initialize_seq_data_loader_dict_1
  - method: initialize_seq_data_loader_dict_2
  - method: initialize_seq_domain_config_1
  - method: initialize_seq_domain_config_2
  - method: initialize_dcm_model
  - method: initialize_clf_model
  - method: train_models_cv
    params:
      alpha: 0.1
      beta: 1.0
      gamma: 0.001
      delta: 0.001
      save_freq: 50
      use_latent_discriminator: True
      use_latent_structure_model: True



